### ISSUE TITLE
adaro/lib/patch/index.js:121:21: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by prabhash1785** [krakenjs/adaro#93]
After I updated dustjs modules in my Kraken application, I get following error while rendering the dust page:

```
TypeError: Cannot read property 'name' of undefined
   at applied (/abc/GitRepo/sampleApp/node_modules/adaro/lib/patch/index.js:121:21)
   at notApplied (/abc/GitRepo/sampleApp/node_modules/adaro/lib/patch/index.js:126:13)
   at Object.apply (/abc/GitRepo/sampleApp/node_modules/adaro/lib/patch/index.js:113:13)
   at View.engine (/abc/GitRepo/sampleApp/node_modules/adaro/lib/engine.js:92:15)
   at View.render (/abc/GitRepo/sampleApp/node_modules/express/lib/view.js:93:8)
   at EventEmitter.app.render (/abc/GitRepo/sampleApp/node_modules/express/lib/application.js:530:10)
   at ServerResponse.res.render (/abc/GitRepo/sampleApp/node_modules/express/lib/response.js:933:7)
   at ServerResponse.res.render (/abc/GitRepo/sampleApp/node_modules/logger/index.js:164:20)
   at ServerResponse._analytics.res.render (/abc/GitRepo/sampleApp/node_modules/analytics-xxx/lib/node-analytics.js:172:16)
   at serverError (/abc/GitRepo/sampleApp/node_modules/kraken-js/middleware/500.js:30:17)
```

These are my dustjs modules:

```
"dusthelpers-supplement": "^1.0.0",
    "dustjs-helpers": "^1.7.3",
    "dustjs-linkedin": "^2.7.0",
    "ppdustjs-filters-secure": "0.0.2",
    "grunt-dustjs": "^1.2.1"
```

My view engine configuration in config.json:

```
"view engines": {
        "js": {
            "module": "engine-munger",
            "renderer": {
                "method": "js",
                "arguments": [
                    { "cache": true, "helpers": [ "ppdustjs-filters-secure", "dustjs-helpers" ] },
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    },
```

Any idea why adaro is throwing this error? Is there a specific dustjs version which needs to be used to resolve this error?

**Comment by aredridel** [comment]
Which version of adaro? 

dust 2.7 is not compatible with engine-munger 0.2.x

**Comment by prabhash1785** [comment]
I have adaro 0.1.7 and engine-munger 0.2.4

Let me try to update adaro to 2.0.0-4 and egnine-munger to 1.1.1 and see if this resolves the issue.

**Comment by prabhash1785** [comment]
Nope, updating adaro and engine-munger to latest version did not help.

Finally I downgraded my dust version to 2.6.2 and everything works now. Here are the versions I am using:

```
"adaro": "~0.1.7",
"dusthelpers-supplement": "~0.0.4",
"dustjs-helpers": "~1.6.3",
"dustjs-linkedin": "~2.6.2",
"engine-munger": "^0.2.4"
```

**Comment by prabhash1785** [comment]
By the way, lets say if I have to use Dust version 2.7 then what version of engine-munger and adaro are supposed to be used or are they not compatible at all?

**Comment by aredridel** [comment]
engine-munger 1.0.0, adaro 1.0.0, dust 2.7 go together -- it was the focus of my major rewrite, since dust 2.7 (Beware! no semver in dust!) removed the `load` method that they all tweaked.

**Comment by aredridel** [comment]
Check out http://krakenjs.com/2015/07/06/new-i18n-for-dust.html and http://krakenjs.com/2015/07/09/upgrading-makara.html for an intro.

**Comment by prabhash1785** [comment]
Cool! Good to know! Thanks for your help, @aredridel!

I will close this issue.
